/*
 * WinAFL Harness — Auto-generated by winafl-harness-builder
 *
 * Target:  gdiplus.dll
 * Offset:  0x41040
 * Style:   dll_export
 * Args:    2
 *
 * Build:
 *   cl.exe /nologo /W3 /O2 harness.c /link /OUT:harness.exe
 *
 * Verify:
 *   drrun.exe -c winafl.dll -debug
 *     -target_module harness.exe -target_offset 0x<HARNESS_FUNC_RVA>
 *     -fuzz_iterations 10 -nargs 2
 *     -- harness.exe input.bin
 *
 * Fuzz:
 *   afl-fuzz.exe -G -i in -o out -t 2000
 *     -D <DynamoRIO> --
 *     -target_module harness.exe -target_offset 0x<HARNESS_FUNC_RVA>
 *     -coverage_module gdiplus.dll
 *     -fuzz_iterations 5000 -nargs 2
 *     -- harness.exe @@
 */
#include <windows.h>
#include <stdio.h>

#define TARGET_DLL "gdiplus.dll"

/* Adjust the typedef to match the exported function's real signature.
 * Use: dumpbin /exports gdiplus.dll
 * Then look up the function in IDA/Ghidra to confirm args. */
typedef int (WINAPI *TargetFunc)(const wchar_t* input_path);

int fuzz_target(int argc, char** argv) {
    if (argc < 2) return 1;

    static HMODULE hMod = NULL;
    static TargetFunc pTarget = NULL;

    if (!hMod) {
        hMod = LoadLibraryA(TARGET_DLL);
        if (!hMod) {
            fprintf(stderr, "[-] LoadLibrary failed: %lu\n", GetLastError());
            return 1;
        }
        pTarget = (TargetFunc)((BYTE*)hMod + 0x41040);
        if (!pTarget) {
            fprintf(stderr, "[-] Could not resolve target function\n");
            return 1;
        }
        fprintf(stderr, "[+] Target resolved at %p\n", pTarget);
    }

    wchar_t wpath[MAX_PATH];
    MultiByteToWideChar(CP_ACP, 0, argv[1], -1, wpath, MAX_PATH);

    __try {
        pTarget(wpath);
    } __except(EXCEPTION_EXECUTE_HANDLER) {
        /* swallow */
    }

    return 0;
}

int main(int argc, char** argv) {
    return fuzz_target(argc, argv);
}
